### ISSUE TITLE
Provide a way to set additional headers on the initial HTTP request

### ISSUE THREAD

**Issue by jdm** [cyderize/rust-websocket#10]
This is a requirement for Servo, to allow for things like Cookie headers that the browser environment must send.

**Comment by BenTheElder** [comment]
This exists(?)
Create your request via new, or connect, etc..
Then you can manipulate the public 'header's field in the WebSocketRequest struct.

http://cyderize.github.io/rust-websocket/doc/websocket/handshake/request/struct.WebSocketRequest.html

via:

http://cyderize.github.io/rust-websocket/doc/websocket/header/struct.Headers.html

you can then call send etc,

http://cyderize.github.io/rust-websocket/doc/websocket/handshake/request/struct.WebSocketRequest.html#method.send

**Comment by jdm** [comment]
Oh, excellent! I misread it and assumed that the connection was opened immediately.

**Comment by BenTheElder** [comment]
Quick check on the source verifies that 'connect' indeed still just sets up the tcp stream but refrains from sending the request, you still need to call send() on the request after connect or new.
