### ISSUE TITLE
Convert messages into semantic types on receive.

### ISSUE THREAD

**Issue by illegalprime** [cyderize/rust-websocket#108]
Currently you need to convert a text message into a string when you receive it (you can only receive messages in an `Cow<'a, [u8]>` right now). This makes some autobahn tests fail (i.e. if it is an incorrect UTF-8 message the connection should close).

Also, it's nicer for users if messages of a certain type are parsed as that type.
But is closing the connection when an invalid frame arrives too strong?

**Comment by oberstet** [comment]
> But is closing the connection when an invalid frame arrives too strong?

FWIW, this is required by RFC6455 ("fail the connection") for a compliant implementation.

**Comment by illegalprime** [comment]
@oberstet good catch, where is that in the RFC?
Since that's the case I think this should definitely be implemented.

**Comment by oberstet** [comment]
@illegalprime see [here](https://tools.ietf.org/html/rfc6455#page-48) and [here](https://tools.ietf.org/html/rfc6455#page-43)

**Comment by illegalprime** [comment]
@oberstet thank​ you!
