### ISSUE TITLE
Client/Server examples fail

### ISSUE THREAD

**Issue by bschwind** [cyderize/rust-websocket#114]
With a fresh checkout on commit `9cacbd3` on OS X 10.12.3

Run

```
cargo run --example server
```

and in another tab:

```
cargo run --example client
```

Running the client yields:

```
Connecting to ws://127.0.0.1:2794
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResponseError("Status code must be Switching Protocols")', src/libcore/result.rs:859
```

The status code is `BadRequest`

**Comment by illegalprime** [comment]
@bschwind thanks for the report I'll take a look! In the meantime I'm sure that the Autobahn Server/Client example works, since that example is how we test this crate.

**Comment by illegalprime** [comment]
The error was that the client wasn't specifying it was using the `rust-websocket` protocol.
To be extra clear, 'protocols' in websockets are user defined and do not mean anything on the websocket level, they are just a way for user code to organize connections. So the examples would have worked if neither party specified a protocol, or if the server wasn't checking for it.

**Comment by bschwind** [comment]
Got it, thanks for fixing that so quickly!
