### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [cyderize/rust-websocket#118]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by illegalprime** [comment]
yay! `serde` is a cooler name anyway. Thanks for the info

**Comment by illegalprime** [comment]
Anyone is free to start working on this, currently `tokio` is my priority.

**Comment by illegalprime** [comment]
Fixed by #122
