### ISSUE TITLE
Server<NoSslAcceptor> has no method set_nonblocking()

### ISSUE THREAD

**Issue by poidl** [cyderize/rust-websocket#120]
I'm a beginner and noticed that `Server<NoSslAcceptor>` has no method `set_nonblocking()` but `Server<SslAcceptor>` does. 

Is there a reason for this? In the previous release of rust-websockets this was possible. Thanks for your help!

**Comment by illegalprime** [comment]
Hmm great point. This is definitely a bug. I'm moving from Atlanta to Nashville right now and pretty hung over. I'm happy to accept a PR though, if not I'll get to it pretty soon but this might be good stuff for a beginner.

The best way is to add a bunch of common `TcpListener` functions and then add a function that gives you direct access to the `TcpListener` or SSL listener as a catch all. Best of luck!

**Comment by poidl** [comment]
Awesome, thanks for mentoring!

> The best way is to add a bunch of common TcpListener functions and then add a function that gives you direct access to the TcpListener or SSL listener as a catch all. Best of luck!

Not sure if I follow, are you saying it's sufficient to remove the `set_nonblocking()` method from the SSL-specific server implementation to the non-SSL-specific implementation? Like:

```
impl<S> Server<S>
    where S: OptionalSslAcceptor
{
	pub fn local_addr(&self) -> io::Result<SocketAddr> {
		...
	}
	pub fn try_clone(&self) -> io::Result<Server<S>> {
		...
	}
	pub fn set_nonblocking(&self, nonblocking: bool) -> io::Result<()> {
		self.listener.set_nonblocking(nonblocking)
	}
}
```

**Comment by illegalprime** [comment]
I don't think there needs to be a new trait here. Probably moving stuff into `Server<S>` is the best bet. In the client connection there are a lot of convenience methods like this that just call the inner stream's methods

**Comment by poidl** [comment]
I tried to issue a PR but the CI tests failed. Not sure what the reason is. Unfortunately I'm out of time now, maybe I'll take a closer look at it next weekend!

**Comment by illegalprime** [comment]
Sometime the tests fail with `fatal runtime error: out of memory`, I have to fix that but for now I just re-run it.

**Comment by poidl** [comment]
Noted, thanks!

**Comment by poidl** [comment]
I tried to come up with a test, but got stuck. Frankly, I really have no idea what I'm doing here. The idea was simply to test

- if the `.set_nonblocking(true)` yields `Ok`
- if `.accept()` yields an error (which is expected)

The test runs fine with the insecure server, but fails with the SSL server. That's because I copied the [example code](http://cyderize.github.io/rust-websocket/doc/websocket/server/struct.Server.html) for setting up the Ssl server, which reads a non-existing file `identity.pfx`. I saw that you opted out of actually running those tests with the `no_run` option, that's why the doc-tests pass.

Could you comment on whether [this](https://github.com/poidl/rust-websocket/commit/bb97fc5a31dfcff426fdd79033e8e926062167f3) make any sense? (compiles but still panicks due to the `identity.pfx`) 

And how to test the Ssl server?

**Comment by illegalprime** [comment]
@poidl I would do some doc tests showing how to use it with SSL / non SSL with `no_run` on, and one real test that tries to accept something but fails with the correct error, which will probably be `io::ErrorKind::WouldBlock`, but I actually don't remember. Good luck!

**Comment by illegalprime** [comment]
Closing because #121 was merged.
