### ISSUE TITLE
wss client without split

### ISSUE THREAD

**Issue by alex-shapiro** [cyderize/rust-websocket#125]
I'm upgrading from 0.17 to 0.19 and it looks like splitting a generic client (one that supports both WS and WSS) into its Sender and Receiver components is no longer possible because `SslStream` doesn't  implement `Splittable`. Up to now splitting the client has been the idiomatic way to do things (at least in the examples) - is there a way around this limitation?

**Comment by illegalprime** [comment]
You cannot split `SslStream` into it's read and write components because of how SSL works.
Why not use the same client struct for both reading and writing? Or wrap it in a `Mutex`?

**Comment by alex-shapiro** [comment]
Splitting the client into a `Reader` and `Writer` lets a program send and receive messages simultaneously, and as best I can tell, a single client struct cannot do that. If the client begins listening for incoming messages:

```rust
for message in client.incoming_messages() {
  ...
}
```
then it blocks the thread. Even if the client is wrapped in a `Mutex`, the resource is locked for as long as the client listens - if it listens for the lifetime of the program, other threads can't send messages at all.

**Comment by illegalprime** [comment]
You can use:
```rust
let message = client.recv_message().unwrap();
let _ = client.send_message(message);
.
.
.
```

If you want asynchronous stuff, that's coming very soon #6

**Comment by alex-shapiro** [comment]
Ok, it seems like waiting for Tokio support is the best way forward.

**Comment by vi** [comment]
Inability to split seems to be very restrictive: connection becomes half-duplex.

Why was it working before, in <0.19?

**Comment by illegalprime** [comment]
@vi the previous implementation was wrong, you cannot have independent streams for reading and writing SSL. This is definitely a problem, but it's being addressed, are you familiar with tokio? Would you mind helping me figure it out?

**Comment by vi** [comment]
@illegalprime, I tried building and running some Tokio example recently, but it's probably not enough to offer advice. Also not all parts of Tokio are stable enough.

Does Hyper and some ssl already support Tokio?

**Comment by illegalprime** [comment]
@vi yeah async stuff is crazy right now, I have a tokio example almost working, I'll publish it for clients as soon as I can!

**Comment by illegalprime** [comment]
@alex-shapiro @vi  I just got the autobahn client tests passing for my tokio implementation, so it's coming along. You can try it out if you want on `feat/tokio` branch.

**Comment by vi** [comment]
Can one use Tokio just to simulate splitting the SSL stream in two, without changing the entire application architecture?

**Comment by illegalprime** [comment]
@vi yes it can! I've already done it with a non SSL connection and there is no API difference I can tell with `tokio-tls`

**Comment by illegalprime** [comment]
In your opinion, do you think you should be able to use both sync and async apis or that turning one feature on should turn the other off? And any other API opinions would be welcome.

**Comment by vi** [comment]
Before answering such questions I need to experiment a bit with the aforementioned example.

**Comment by illegalprime** [comment]
OK, take a look at that branch it should have a couple of examples right now.

**Comment by vi** [comment]
Is it typical that Tokio examples are longer than usual synchronous examples?

**Comment by illegalprime** [comment]
In the autobahn they are longer, I'm also trying to figure tokio out and maybe there's a better way to do what I'm doing. Sometimes they can be smaller though, check out `examples/async-client.rs`.

**Comment by illegalprime** [comment]
@vi just realized I hadn't committed that file, it should be there now.

**Comment by illegalprime** [comment]
@alex-shapiro the `tokio` API is getting pretty stable, you can try it out if you want like OP did in #127 .
You would replace your `websocket` dependency with this in your `Cargo.toml`:
```toml
[dependencies.websocket]
git = "https://github.com/cyderize/rust-websocket"
branch = "feat/tokio"
```

**Comment by TomCrypto** [comment]
I've run into this issue as well with the sync client, does it actually make any sense to use a sync client with SSL since it's (allegedly) impossible to read from and write to it at the same time? If you are busy sending stuff you can never respond to messages, which wouldn't be such a big deal except that a client should normally respond to pings even if all it does is send. Seems to make the sync client essentially broken by design in most nontrivial cases, and forces the user towards the mess that is async...

**Comment by vi** [comment]
Maybe you could just `unsafe` it and hope for the best?

 (e.g. hope that some SSL re-negotiation won't be triggered while you are sending something)
