### ISSUE TITLE
Error kills server, preventing new connections.

### ISSUE THREAD

**Issue by enzious** [cyderize/rust-websocket#130]
I'm using a modified version of the example and a benchmark I'm using throws a "Missing Sec-WebSocket-Key header" error. After receiving this error, the server stops listening. Printing no further errors, but still allowing older connections to close properly.

```rust
Server::bind(&addr, &core_handle).unwrap()
        .incoming()
        .map_err(|InvalidConnection { error, .. }| {
          println!("error: {}", error);
          error
        })
        .and_then(move |(upgrade, addr)| {
          println!("and_then");

          handle.spawn_future(
            client_handle(&handle, (upgrade.use_protocol("rust-webscoket"), addr)),
            "ClientAcceptor",
          );

          Ok(())
        })
        .or_else(|_| {
          println!("or_else");

          Err(())
        })
        .for_each(|()| {
          println!("for_each");

          Ok(())
        })
```

Am I doing something wrong?

**Comment by illegalprime** [comment]
Well in `futures-rs` streams any error along the stream will stop the stream entirely, I think your trouble might be here:

```rust
        .map_err(|InvalidConnection { error, .. }| {
          println!("error: {}", error);
          error
        })
```

This makes every invalid connection an error and stops new connections. I would try using [`.or_else`](http://alexcrichton.com/futures-rs/futures/stream/trait.Stream.html#method.or_else) instead of `.map_err` to recover from the error (maybe just ignore it). Let me know if that doesn't work, I'm in the office away from this project.

**Comment by enzious** [comment]
This worked:
```rust
    Server::bind(&addr, &core_handle).unwrap()
        // Get a Stream of incoming clients.
        .incoming()
        // Handle Ok result/client.
        .for_each(move |(upgrade, addr)| {
          handle.spawn_future(
            client_handle(&handle, (upgrade.use_protocol("rust-webscoket"), addr)),
            "ClientAcceptor",
          );
          Ok(())
        })
        // Ignore errors.
        .or_else(|_| {
          Ok(())
        })
```

**Comment by illegalprime** [comment]
Awesome, I'm glad to see you found it! Thanks for reporting the issue also, I'll add it to the examples.
