### ISSUE TITLE
Debug impl for MessageCodec

### ISSUE THREAD

**Issue by dbrgn** [cyderize/rust-websocket#145]
Would it be possible to implement the Debug trait for the `MessageCodec` type?

It would make debugging much easier :) Right now the "message" returned by an async stream can't be logged/printed directly.

**Comment by dbrgn** [comment]
I think this issue is a result of my misunderstanding of stream combinators. I was mistaking the `MessageCodec` for the `OwnedMessage` :)

**Comment by illegalprime** [comment]
Glad you figured it out!
