### ISSUE TITLE
What is the relationship between the 'websocket' and 'servo-websocket' crates?

### ISSUE THREAD

**Issue by faern** [cyderize/rust-websocket#147]
On crates.io there is one crate named [`websocket`](https://crates.io/crates/websocket) and one named [`servo-websocket`](https://crates.io/crates/servo-websocket). Both of them reference this repository as their repository.
* The crates are seemingly identical in their documentation.
* The `websocket` crate has cyderize as owner, which is the same user as this repo is under.
* The `websocket` crate has existed much longer.
* The `servo-websocket` crate has a newer published version, but with a lower version number than the latest `websocket` version.

Are there any differences between the crates? why do both exist? and which one should one typically use?

**Comment by illegalprime** [comment]
`servo-websocket` is an older version used in servo with some hotfixes that they needed to be in crates.io that could not be merged and published in time to meet their schedule (from what I understand). Now as far as I'm aware all of those fixes (and more features) have been added to this crate.

**Comment by faern** [comment]
Ok. So anyone, except Servo, should use the `websocket` crate then. Everything I wanted to know has been answered :)
