### ISSUE TITLE
Request parsing should be done in a separate thread

### ISSUE THREAD

**Issue by barosl** [cyderize/rust-websocket#22]
I'm not sure I fully understand the situation, but let me explain. While running a server, it seems that some laggy clients can slow down the entire `accept()`ing process on the server.

According to the `gdb` stack trace, it is sometimes stuck as follows:

```
#0  0x00007ffff72b755d in read () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055555561e2fa in net::tcp::TcpStream.Read::read::hcc8bbd2f6c31c9d1o7m ()
#2  0x00005555555af2c4 in websocket::stream::WebSocketStream.Read::read (self=0x7fffffffc750, buf=...) at /home/barosl/.cargo/git/checkouts/rust-websocket-3ef83361cb9b03c6/master/src/stream.rs:19
#3  0x00005555555af052 in fnfn (b=...) at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/io/buffered.rs:96
#4  0x00005555555aedc3 in websocket::io::with_end_to_cap<closure> (v=0x7fffffffc780, f={union Result<usize, std::io::error::Error> (struct (&mut [u8]))} 0x7fffffffb420)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/io/mod.rs:77
#5  0x00005555555ae94d in websocket::io::buffered::BufReader<R>.BufRead::fill_buf (self=0x7fffffffc750)
    at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/io/buffered.rs:96
#6  0x00005555555adc8c in websocket::http::parse_request<std::io::buffered::BufReader<websocket::stream::WebSocketStream>> (buf=0x7fffffffc750)
    at /home/barosl/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.3.2/src/http.rs:313
#7  0x00005555555ad492 in websocket::server::request::Request<R, W>::read (reader=..., writer=...) at /home/barosl/.cargo/git/checkouts/rust-websocket-3ef83361cb9b03c6/master/src/server/request.rs:85
#8  0x00005555555ac426 in websocket::server::Server<'a>::accept (self=0x7fffffffd900) at /home/barosl/.cargo/git/checkouts/rust-websocket-3ef83361cb9b03c6/master/src/server/mod.rs:139
#9  0x00005555555b07a5 in websocket::server::Server<'a>.Iterator::next (self=0x7fffffffd900) at /home/barosl/.cargo/git/checkouts/rust-websocket-3ef83361cb9b03c6/master/src/server/mod.rs:156
```

As you can see, it is indefinitely waiting for the client to respond with the request header. That means, the following code in `src/server/mod.rs` is problematic:

```rust
match Request::read(try!(wsstream.try_clone()), try!(wsstream.try_clone())) {
```

I believe this is because, currently, the request parsing is done in the main thread. To cope with this, the parsing should be delegated to the client thread. But it is not possible, as there is no other way to parse the request manually other than relying on `Server::accept()`.

So, I think, there should be two separate methods. One for the `TcpStream` acceptance, the other for the usual HTTP parsing. The iterator for `Server` should process only the former, and the latter may be processed in a separate thread.

Am I right? What do you think on this?

**Comment by cyderize** [comment]
Can you please check if the branch 0.11.3 is a sufficient change?
I've thought that the reading of requests should be done on a different thread, but somehow that got lost along the way.

Thanks

**Comment by barosl** [comment]
Yes, it seems to be fixed now. Thanks!
