### ISSUE TITLE
wss HttpTooLargeError

### ISSUE THREAD

**Issue by fuchsnj** [cyderize/rust-websocket#23]
I tried running the "secure server" example at http://cyderize.github.io/rust-websocket/doc/websocket/server/struct.Server.html

but whenever a websocket client connects to the server, the server fails with
```
Failed to read request (HttpError(HttpTooLargeError))
```

It works if I use the non-secure server, and my ssl cert works in another application.

**Comment by fuchsnj** [comment]
So after some painful debugging, this isn't really a problem with this library. The error that is being returned by hyper (HttpTooLargeError) is incorrect. When the error is returned, the request is actually too small (0 or 1 bytes in my case) and hyper fails to parse the headers and returns the incorrect header.

I was using Chrome as the websocket client while testing this with an invalid certificate (using it on localhost), which for some reason it connects to the websocket server, and rejects the connection the first time (which is where the 0 byte request comes from) then opens the connection again and works the 2nd time.

**Comment by cyderize** [comment]
Yes, I was trying to debug this as well.

I'm thinking this might have something to do with [hyper #389](https://github.com/hyperium/hyper/issues/389), although that one is about clients not servers.

**Comment by seanmonstar** [comment]
The error was in `http.rs`, so it affected both. It should be fixed now.

**Comment by fuchsnj** [comment]
@seanmonstar Thanks!
