### ISSUE TITLE
Create a todo for contributions

### ISSUE THREAD

**Issue by boghison** [cyderize/rust-websocket#27]
I think a TODO list would be great for contributors. It would be much easier than searching in every file for bugs, typos and lack of documentation.

**Comment by boghison** [comment]
@cyderize Could you take a look at this? This library is awesome and I would seriously love to contribute, but I (and potential contributors) need to know what needs to be done :)

**Comment by cyderize** [comment]
I think the TODO list basically consists of:
- Improve the documentation and add more example function usages
- Add more tests and benches
- Figure what's going wrong with the Autobahn client tests
- Add some kind of shutdown method to the server
- Implement permessage deflate

I'll try to write up a more useful TODO at some point.

**Comment by puhrez** [comment]
@cyderize is the above list still relevant?
