### ISSUE TITLE
add .shutdown() method to server

### ISSUE THREAD

**Issue by fuchsnj** [cyderize/rust-websocket#28]
As far as I can tell, it does not seem possible to stop the server and close all of the connections cleanly.

Right now you would need some way to signal to each connection to shut them down,then to break out of the `for connection in server` you would have to wait for another connection to connect and then break (or make one yourself). But this is very messy. It would be great if there was a `shutdown()`  method on the server.

**Comment by cyderize** [comment]
I'm not too sure how this `shutdown()` method would work - I can't think of a non-messy way to do this. Any ideas on how this could be achieved cleanly from within the library?

Otherwise the mess will just be inside instead of outside (which although better, is not great)
