### ISSUE TITLE
get stable-compatible

### ISSUE THREAD

**Issue by blaenk** [cyderize/rust-websocket#37]
I _really_ would love it if this could build on stable. I would love to help wherever I can.

Some approaches I've seen to getting things to build on stable include:

* introducing a cargo feature that enables specific functionality that requires nightly, that is, one feature for each distinct piece of functionality. Then use the `cfg(feature = "blah")` to conditionally compile pieces of code
* alternatively, as above, introduce some 'nightly' feature that toggles _all_ functionality that requires nightly, if it doesn't make sense to provide fine-grained toggling
* rip out the implementations of unstable features that is relied upon from the nightly std and embed it into your own package, at least until the fate of such unstable features is determined

**Comment by cyderize** [comment]
Yes, it would be great to get this to build on stable.

I think the 'nightly' feature idea (since hyper uses nightly and we already export this feature) would be possible. The majority of the library should hopefully still function with stable rust. It might be a bit annoying to use and maintain `cfg(feature = "nightly")` though, but I guess having it work with stable `std` would be worth the effort.

I'll have a go at this later today.

**Comment by blaenk** [comment]
Thanks!

I agree that it's a hassle but I think being stable compatible is a huge
benefit, as you say. It would be nice if rust came up with better ways of
managing the divide between the different channels.

Hope it goes well.

On Sunday, May 17, 2015, Jason N <notifications@github.com> wrote:

> Yes, it would be great to get this to build on stable.
>
> I think the 'nightly' feature idea (since hyper uses nightly and we
> already export this feature) would be possible. The majority of the library
> should hopefully still function with stable rust. It might be a bit
> annoying to use and maintain cfg(feature = "nightly") though, but I guess
> having it work with stable std would be worth the effort.
>
> I'll have a go at this later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyderize/rust-websocket/issues/37#issuecomment-102887324>
> .
>


-- 
- Jorge Israel Peña

**Comment by blaenk** [comment]
Amazing job :+1:

**Comment by cyderize** [comment]
I think the most annoying thing will be that the tests won't work on stable rust.  This makes it that much harder to ensure everything works... I sure hope everything functions correctly.

**Comment by blaenk** [comment]
Yeah, a few other packages I've helped go stable have run into the same issue.
