### ISSUE TITLE
Client::connect does not conform to rfc6455 section-4.1

### ISSUE THREAD

**Issue by Nashenas88** [cyderize/rust-websocket#38]
According to http://tools.ietf.org/html/rfc6455#section-4.1 connect should take a host, port, resource name, and a secure flag, along with a list of protocols and extensions to be used. Currently, it accepts a Url object.

"A client will need to
   supply a /host/, /port/, /resource name/, and a /secure/ flag, which
   are the components of a WebSocket URI as discussed in Section 3,
   along with a list of /protocols/ and /extensions/ to be used."

**Comment by cyderize** [comment]
Hmm, that is a good point. I must've overlooked that part of the specification.

How about a `connect` method and a `connect_url` method? That should allow for conformance and convenience if the user is working with urls.

**Comment by KiChjang** [comment]
That'll be a breaking change though, all existing users of `Client::connect` will have to switch to `connect_url`.

Are you also thinking of calling `connect` within the new `connect_url` method?

**Comment by cyderize** [comment]
Yeah, the idea would be to call `connect()` inside `connect_url()`.

I'm thinking a `Client::connect(host: url::Host, port: u16, resource_name: String, secure: Option<&openssl::ssl::SslContext>` function would meet the specification well enough.

And then `Client::connect_url(url: url::Url)` will just extract the required bits and call `connect()` as a convenience for those who are only working with URLs and don't care about the components.

Since I myself need to parse the URLs and get the components, I could probably put the conformant URL parsing in a utility function (`parse_url(url: Url) -> WebSocketResult<(url::Host, u16, String, bool)>`) which could then be used by Servo (unless Servo needs to do something more complex in terms of parsing).

I'm not too concerned about breaking changes since we're pre 1.0.0, although it probably a good idea to avoid them, I'd prefer to have the most 'obvious' connect function the one that follows the specification.

**Comment by Nashenas88** [comment]
According to http://tools.ietf.org/html/rfc6455#section-3 (referenced from section 4.1), secure looks like it should be a boolean. It also matches https://html.spec.whatwg.org/multipage/comms.html#parse-a-websocket-url's-components , particularly step 8.

**Comment by cyderize** [comment]
The problem with a boolean flag is that it doesn't allow the user any control over the SslContext used. I'd rather the user be able to specify their own context (so they can choose their required SSL/TLS versions, etc) than to just force a particular context.

Ah yes, that looks great, I'd love to use what you've written (with your permission, of course).

**Comment by Nashenas88** [comment]
If you have an interface in mind, I could add the pull request first. I could replace what I have in servo with that at the same time you're writing the update to connect.

**Comment by cyderize** [comment]
What I have in mind is replacing `url_to_host()` in `websocket::ws::util::url` (`src/ws/util/url.rs`) with `parse_url(url: Url) -> WebSocketResult<(url::Host, u16, String, bool)>`.

It would be great if you could add `parse_url(url: Url) -> WebSocketResult<(url::Host, u16, String, bool)>` to the file `src/ws/util/url.rs`, and I'll do the replacement of the function.

**Comment by Nashenas88** [comment]
I'm working on it now, but I have a couple questions:

1. Do you want me to open an issue, or just submit a PR when I'm done?
2. `WebSocketResult` doesn't have an error condition that makes sense for this case (The RFC for this implementation says to just fail the algorithm). Do you want me to add one for each case, or just one called `WebSocketUrlError`?
3. `url::Host` already contains the host and port number. Wouldn't `WebSocketResult<(url::Host, String, bool)>` or `WebSocketResult<(String, u16, String, bool)>` be better?

**Comment by cyderize** [comment]
A PR would be fine, I think. Thanks so much for doing this.

We can probably just replace `UrlError(ParseError)` in `websocket::result::WebSocketError` with a more suitable error kind like `UrlError(UrlErrorKind)`, and have a `UrlErrorKind` for each case. Or we could even use a plain `UrlError` enum variant if that's easier.

Ah, yeah, `WebSocketResult<(url::Host, String, bool)>` would be perfect. I forgot that `url::Host` has the port as well.

**Comment by Nashenas88** [comment]
No worries. Working with rust and on servo has been a lot more fun than I expected :).

I think `UrlError(ParseError)` is still valid. I was thinking it'd be really useful to also have `parse_url_str(url_str: &str) -> WebSocketResult<(hyper::header::Host, String, bool)>` since some people might be creating sockets from user input (especially in servo's case). Also, it looks like `url::Host` isn't what we want, but instead `hyper::header::Host`. I've already created `parse_url_str` locally since it was part of my original code base. It just calls `parse_url` after it parses the url string and verifies it was a valid url. That's where I'll still be returning a `WebSocketError::UrlError(ParseError)`.

What about a `WebSocketError::WebSocketUrlError(WSUrlErrorKind)`? That would differentiate it from a more general url.

**Comment by cyderize** [comment]
Yeah, that sounds awesome.

Indeed `hyper::header::Host` would be the most appropriate and useful host type. I guess a `parse_url_str` would be convenient for some people, so it makes sense to include it. `WebSocketError::WebSocketUrlError(WSUrlErrorKind)` sounds good.

**Comment by Nashenas88** [comment]
I've got a PR up at #40.

**Comment by cyderize** [comment]
As of 0.12.0, `Client::connect` can accept anything that implements `ToWebSocketUrlComponents`, which means you can now specify a URL (for convenience), or the required components (host, port, resource_name, secure) to initiate a connection.

Hopefully this means Servo can do what it needs to do to conform to specification.

Thanks to @Nashenas88 for PR #40.

I consider `Client::connect`, `Request.send`, `Response.validate` and `Response.begin` to together `_Establish a WebSocket Connection_`, and I believe this is now done in conformance with section 4.1 of RFC6455, or at least as close as I can get it for now.

**Comment by Nashenas88** [comment]
I'd say this meets the spec now. I'll be closing the issue. Thanks for working together on this. It was a lot of fun! I have a cleanup PR coming that simplifies a couple things in PR #40 a little bit.

**Comment by Ms2ger** [comment]
Moved to this in https://github.com/servo/servo/pull/6634
