### ISSUE TITLE
Server works for Firefox but not for Chrome

### ISSUE THREAD

**Issue by nicksanders** [cyderize/rust-websocket#41]
When I run the examples server and autobahn-server they fail in Chome but work in Firefox

The server fails with one of the message below 

    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NoDataAvailable', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729
    
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os(32) })', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729

Chrome's error message is below

    WebSocket connection to 'ws://127.0.0.1:2794/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

One difference I can see in the request headers is Chrome has client_max_window_bits in its Sec-WebSocket-Extensions header

    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Firefox**
GET / HTTP/1.1
Host: 127.0.0.1:2794
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: null
Sec-WebSocket-Protocol: rust-websocket
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: lDZ28g1qsvq2+z4hj7hUzQ==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 101 Switching Protocols
Sec-WebSocket-Accept: fhZDselY5dBr8uW+eFXcOtdkUXw=
Connection: Upgrade
Upgrade: websocket

..Hello

**Chrome**
GET / HTTP/1.1
Host: 127.0.0.1:2794
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: null
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en;q=0.8
Sec-WebSocket-Key: QUrpS70CwiViTEk5g68sBA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Protocol: rust-websocket

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: OPF1GnZv5n7IftL0aFw7ijr3v6c=

..Hello

**Comment by cyderize** [comment]
I think chrome requires the WebSocket-Protocol header to be set in the response (even though as far as I can tell, it shouldn't). If you set the header before sending the response it will probably work.

I should update the example to include he protocol (I thought it already did, but I guess not)

**Comment by cyderize** [comment]
I believe the example server now works with chrome. `autobahn-server` isn't intended to work with browsers, it's supposed to use the fuzzingclient from the autobahn test suite.

**Comment by nicksanders** [comment]
Thanks, yes it works for me in Firefox and Chrome
