### ISSUE TITLE
Example of usage with a HTTP server?

### ISSUE THREAD

**Issue by euclio** [cyderize/rust-websocket#46]
Hello, I'd love to use rust-websocket for a project I'm working on. I'd like to make a server (using iron or hyper) that supports both HTTP connections and WebSocket connections. I imagine this is a common use case. Is this possible with the current API? If so, perhaps a simple example in the docs would be very helpful.

**Comment by cyderize** [comment]
It's certainly possible to run a hyper HTTP server (hyper is most convenient since it's already a dependency of rust-websocket) alongside a websocket server, and it's quite easy to do when they listen on different ports. I've added an example in 1fab3a438a5f11e97760acddfcfd8c9504094987.

It's quite a bit harder if you want them to listen on the same port, but it should still be possible - I'm not sure why you would really need to do that, though.

**Comment by euclio** [comment]
Awesome, thanks. Just for curiousity -- how would you listen on the same port?

**Comment by cyderize** [comment]
Yeah, that's the idea.

Actually, at the moment I don't think it's even possible with the current API - you'd have to do a lot of trickery to get anything close to working, unfortunately. If this was requested, then I could probably add a way to manually create a `websocket::server::request::Request`, which would allow you to pull the appropriate parts from the hyper request and turn it into a websocket one.

**Comment by euclio** [comment]
Great, thanks. I think it'd be a useful feature, but obviously not critical. Thanks for being so responsive and helpful!

**Comment by alexandercampbell** [comment]
+1 to this issue; I have the same use case.

I opened https://github.com/cyderize/rust-websocket/pull/48, so websockets and HTTP on the same port is now technically possible. I hacked together a simple static file server that also serves websockets on `/websocket`. If anyone wants the source I can post the relevant parts. It's pretty simple.

I'm looking into "the right way" to do this. @cyderize does it make sense to you to attach a websocket handler to an existing Hyper server? I don't know much about the existing structure of the project, but I'd be glad to give this feature a shot.

Thanks.

**Comment by kevincox** [comment]
This would be really cool to see. It is really nice to have all of your API behind the same hostname and http endpoint.

**Comment by Paxa** [comment]
I was able to make normal web server and websocket on same port. But it requires a lot custom code.

```rust

pub struct RequestWrap {
    pub method: String,
    pub url: String,
    pub headers: Headers,
    pub body: String,
}


thread::spawn(move || {
    let request = connection.unwrap().read_request().unwrap();
    let headers = request.headers.clone();
    let path = request.url.to_string();

    if !headers.has::<header::Upgrade>() {

        let web_request = RequestWrap {
            method: request.method.as_ref().to_string(),
            url: request.url.to_string(),
            headers: request.headers.clone(),
            body: request.body.clone()
        };

        let response = WsResponse::bad_request(request);
        let (_, writer) = response.into_inner();

        webserver::handle(web_request, writer, sender);
        return;
    } else {
        // process as normal web socket
    }
});
```

**Comment by mattiasflodin** [comment]
Here are some points on why you would prefer to use the same port for the websocket: http://stackoverflow.com/a/28524997
