### ISSUE TITLE
Non-owning Message sending.

### ISSUE THREAD

**Issue by meh** [cyderize/rust-websocket#49]
Is there a way, or could it be possible to add one, to send messages without having to allocate?

Basically having something like a `MessageRef` or using `Cow` so an allocation isn't required.

My use-case is I'm sending a pretty big `Vec<u8>` to multiple clients at 30 FPS, and right now I have to clone the vector for every client.

**Comment by illegalprime** [comment]
I just ran into this problem myself, I'll try to fork this lib and take a look. My use case is that when the connection fails I want to still have a reference to the Message, right now I have to clone every time in case the message fails to send.

**Comment by cyderize** [comment]
@illegalprime, a pull request would be great, if you can figure out something.

I haven't got much time to work on this library right now (end of year exams are coming up, unfortunately). But when I have time, I'll definitely look into this.

**Comment by illegalprime** [comment]
Glad to help! I'm working on it now.
Using a `Cow` inside of `DataFrame` seems to be the most straightforward solution so far, but adding a lifetime parameter to `DataFrame` means adding lifetime parameters to so many other things! It's getting messy; maybe I'll do something else.

**Comment by illegalprime** [comment]
@cyderize `DataFrame` now has a `Cow` in it, this involved changes to almost the entire library. There is one last method which needs to be implemented, although I can't figure out how. Maybe you or @meh can [help me](https://github.com/illegalprime/rust-websocket/blob/iter-impl/src/message.rs#L88).

**Comment by meh** [comment]
@illegalprime looks like you'll have to write your own thing implementing `Iterator` instead of using a pre-existing one like it's done there.

**Comment by illegalprime** [comment]
@meh I'm not sure I follow. The main problem is that I want to create an iterator by borrowing internal data:

`fn iter<'d>(&'d self) -> Iter<DataFrame<'d>>`

But defining the above method in a generic trait is tough:

```
trait<D> Message<D> {
    type Iter: Iterator<Item = D>
    fn Iter<'d>(&'d self) -> Iter
}
```
I can't seem to specify a lifetime for D...

**Comment by meh** [comment]
```rust
impl<'d> ws::Message<DataFrame<'d>> for Message {
	fn iter(&self) -> DataFrameIterator {
		...
	}
}

struct DataFrameIterator<'d> {
	...
}

impl<'d> Iterator for DataFrameIterator<'d> {
	type Item = DataFrame<'d>;

	fn next(&mut self) -> Option<Self::Item> {
		...
	}
}
```

Something like this should work.

**Comment by illegalprime** [comment]
@meh It turns out that the implementation of `iter` was correct, but thank you for your suggestion!

In short this works great:
`sender.send_message(&message);`

This crashes and burns (this method only wraps around the above):
`client.send_message(&message);`

I've simplified the problem on rust playground: http://is.gd/ujjRRO
If you or @cyderize can get the above snippet to compile then we will be well on our way to fixing this.

**Comment by illegalprime** [comment]
solved by the good people at SO: https://stackoverflow.com/questions/33116047/borrow-inner-data-from-struct-in-a-wrapper-function
