### ISSUE TITLE
Add method to "upgrade" hyper request to a WebSocket.

### ISSUE THREAD

**Issue by kevincox** [cyderize/rust-websocket#53]
Currently the HTTP request is parsed inside of the library. It would be nice if there was a way to check if an existing hyper `Request` is a websocket request, and if so provide a way to "upgrade" it into a websocket connection. This allows using hyper as a HTTP server and accepting websockets on the same port.

This is similar to how the ruby library [faye-websocket](https://github.com/faye/faye-websocket-ruby) works. You can check the env (essentially a standard request format) if it is a websocket, and if so "upgrade" it into a websocket connection.

**Comment by illegalprime** [comment]
+1 seems like a good idea. This is like #46 (which never got fixed I'm pretty sure). I was leaning towards getting rid of hyper as a dependency so whatevery the fix is it should be able to fit with every http implementation out there.

**Comment by illegalprime** [comment]
@kevincox working on it now on my [fork](https://github.com/illegalprime/rust-websocket). Do you have any opinions about what the API should be?

**Comment by kevincox** [comment]
I imagine something like taking a hyper `Request` and `Response` and returning a websocket `Client`. I imagine setting response headers can be done before passing the `Response` to the method.

**Comment by illegalprime** [comment]
It's not enough to pass a `Response` to make a client, you need the socket too. The two methods I'm thinking of are passing in a stream (like

**Comment by kevincox** [comment]
I thought the `Response` had an output stream? Or is that not enough?

The problem with that API is that (IIUC) it reads the request itself (or at least the Headers). The reason I wanted to "upgrade" the request manually is so that I can do routing, authentication and whatever else I want based on the headers. Your method allows me to route requests if it isn't a websocket connection but doesn't give me the option if it is.

**Comment by illegalprime** [comment]
Your right, I wasn't familiar with hyper's `Request`s. As long as the network stream is bundled with the request data it should be possible. There just needs to be a definitive way to match the upgrade request with the network stream (there is in hyper's `Request`). As for the method signature:

```rust
impl IntoWebSocket for Reqeust {
    fn into_ws(self) -> Result<(&mut Self, Client), (Self, Err)> {
        // ...
    }
}
```

Would you rather `Client` own the network stream / `Request` or just borrow it? If you just want to route requests then I would assume it would be OK to let the Client own it.

Since I'm not familiar with hyper it would help to know what code you _would_ want to write to do this.

**Comment by kevincox** [comment]
I imagine owning it would be fine. I don't think there is any legitimate use of using it after a websocket connection has ended.

**Comment by dns2utf8** [comment]
Is there any progress on this?

**Comment by illegalprime** [comment]
@dns2utf8 I just made #80 , does that API seem like it would be useful to you?

**Comment by illegalprime** [comment]
@kevincox @dns2utf8 this is implemented now.
