### ISSUE TITLE
one client, one thread?

### ISSUE THREAD

**Issue by daogangtang** [cyderize/rust-websocket#6]
In rust and rust-websocket, how to keep the connection for each client persion?
if one client, one thread, can reach 10k connections in single server machine?

**Comment by zrneely** [comment]
I'm also looking into using this library, and I'd like to avoid the 1-to-1 client-to-thread model. It looks like Mio supports Windows as of version 0.5. @daogangtang, are you planning on creating a pull request?

@cyderize, what do you think a good asynchronous model for websocket connections would look like?

**Comment by chpio** [comment]
https://github.com/diesel-rs/diesel/issues/399

**Comment by illegalprime** [comment]
@zrneely It is definitely a goal, it is on my queue but if you want to give it a go that would be cool. :smiley:

**Comment by bgourlie** [comment]
Since hyper is now using evented IO, does that mean that rust-websocket is too?

**Comment by illegalprime** [comment]
@bgourlie where does hyper start using evented IO? and if it does, then its not exposed as evented currently in the library

**Comment by bgourlie** [comment]
No idea, I made that comment 7 months ago and have lost all context. Something must have given me the impression that it did, but I don't know what.

**Comment by comtihon** [comment]
@illegalprime 
Hi,
in https://github.com/hyperium/hyper/pull/778 hyper switched to mio. And as for current master, there is no mio in deps, but I found tokio there. I guess, they switched to it as tokio desired to be faster.
Are you planning to switch to latest hyper?
One thread per client is not good architecture...

**Comment by illegalprime** [comment]
@comtihon yes we are currently planning on including `tokio` support, you can see progress on #111 and you can use that branch if you want. We will switch to the latest `hyper` when it gets published.

**Comment by illegalprime** [comment]
Also, one client per thread is **not** the recommended architecture for many connected clients.
One should `.set_nonblocking()` on the stream manually and do a poor man's event loop.
Obviously we want to do better than that, but it's not merged yet.

**Comment by illegalprime** [comment]
@comtihon @daogangtang @bgourlie @zrneely this crate now supports `tokio`, closing.

**Comment by daogangtang** [comment]
nice work!
