### ISSUE TITLE
Unmasked data error

### ISSUE THREAD

**Issue by DenisKolodin** [cyderize/rust-websocket#61]
I have errors with version 0.14:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value:
DataFrameError("Expected unmasked data frame")', ../src/libcore\result.rs:741
```
When I try `hyper` example Chrome also logs:
```
WebSocket connection to 'ws://127.0.0.1:2794/' failed:
A server must not mask any frames that it sends to the client.
```
Any example doesn't work. How to fix?

Env:
64 bit + rustc 1.6.0-nightly (1805bba39 2015-11-26) + Win 10

**Comment by DenisKolodin** [comment]
Looks like `Server` masks ows frames and expects unmasked frames from client...

```
5.  Data Framing

5.1.  Overview

   In the WebSocket Protocol, data is transmitted using a sequence of
   frames.  To avoid confusing network intermediaries (such as
   intercepting proxies) and for security reasons that are further
   discussed in Section 10.3, a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).  (Note
   that masking is done whether or not the WebSocket Protocol is running
   over TLS.)  The server MUST close the connection upon receiving a
   frame that is not masked.  In this case, a server MAY send a Close
   frame with a status code of 1002 (protocol error) as defined in
   Section 7.4.1.  A server MUST NOT mask any frames that it sends to
   the client.  A client MUST close a connection if it detects a masked
   frame.  In this case, it MAY use the status code 1002 (protocol
   error) as defined in Section 7.4.1.  (These rules might be relaxed in
   a future specification.)
```

**Comment by cyderize** [comment]
Are you using the crates.io version or the git version?

Having looked at #59 more closely, I think that may have broke this.

By merging the senders and receivers for servers and clients we stopped masking and unmasking correctly. But I don't think I've included that in the crates.io crate yet, so could you check if you get these masking errors in the crates.io 0.14.0 crate or the 0.13 crates?

**Comment by DenisKolodin** [comment]
Latest crates.io version doesn't export Sender and Reveiver. I need it for precise messages control.
Version 0.12 works well, but it contains `hyper = "*"` dependency that produce openssl versions conflicts when I want to use hyper-0.6.

I've fiх it up with https://github.com/cyderize/rust-websocket/pull/62
Both works well: client and server.
