### ISSUE TITLE
Timeout on `recv_message`

### ISSUE THREAD

**Issue by LaylConway** [cyderize/rust-websocket#66]
Currently as I'm seeing it, an attacker could hold a thread responding to requests hostage as long as they want. I can of course terminate threads after a certain time but this probably has some dangerous side-effects that I don't ever want to happen.

**Comment by xudifsd** [comment]
it not just about security, I also need this functionality, or at least being able to tell if there're any incoming data so my thread could do something else

**Comment by KenanSulayman** [comment]
Any updates on this? :-)

**Comment by BenTheElder** [comment]
In `slack-rs` we handle this by setting timeout on the TCP socket which works well enough for the websocket client at least (see the above PR referencing this issue). Looking over the server API it looks like your accept handler could access the underlying stream and set read/write timeouts similarly.

**Comment by illegalprime** [comment]
@LaylConway currently you can set either a read timeout or you can just set the `TcpStream` to nonblocking. If you're talking about something like [slowloris](https://en.wikipedia.org/wiki/Slowloris_(computer_security)) then I think nonblocking is your best bet.

I do want to add better support for non-blocking though, do you have any preferences on implementation (`mio`, `tokio`, etc.)?

(cc @KenanSulayman for updates)

**Comment by illegalprime** [comment]
@LaylConway @xudifsd @BenTheElder this crate now supports futures with `tokio`, you can have fully asynchronous servers / clients.

**Comment by KenanSulayman** [comment]
Great news, thanks!

**Comment by fenhl** [comment]
Is there a way to send a ping if no messages are received for some amount of time? I'm having trouble figuring out how to get the client back from the future:

```rust
let (opt_msg, client) = tokio::runtime::Runtime::new()?.block_on(
    client.into_future().select2(tokio::timer::Delay::new(Duration::from_secs(5 * 60)))
        .and_then(|either| match either {
            Either::A((msg, _)) => Ok(msg),
            Either::B(((), _)) => unimplemented!() // now I'd like to send a ping, but how do I get the `client`?
        })
)?;
```

**Comment by vi** [comment]
What's in this `_` inside `Either::B`?

**Comment by fenhl** [comment]
It's a <code>[StreamFuture](https://docs.rs/futures/0.1.26/futures/stream/struct.StreamFuture.html)&lt;[Client](https://docs.rs/websocket/0.22.4/websocket/client/async/type.Client.html)&gt;</code>.

**Comment by vi** [comment]
@fenhl , So await it, extracting the `Client`, then send ping, then do 3-way select again, waiting for either some message, ping reply or timeout.

**Comment by fenhl** [comment]
The problem is that the future only completes if a message is received. However, it looks like [`StreamFuture::into_inner`](https://docs.rs/futures/0.1.26/futures/stream/struct.StreamFuture.html#method.into_inner) does what I want.
