### ISSUE TITLE
first websocket messages can be consumed during handshake process

### ISSUE THREAD

**Issue by bobthekingofegypt** [cyderize/rust-websocket#72]
I have been tracking down a series of intermittent failures inside servos test suite to do with Websockets.  The original issue is available here https://github.com/servo/servo/issues/9803 but it's full of crazy thoughts and lots of distractions and is probably best to ignore.

I believe I have tracked down the issue to a problem in the way rust-websocket reads the handshake response and then transfers over to reading the BufReader itself.  What happens is occasionally when hyper reads the handshake response into the buffer it also pulls with it the next message(s) aswell.  So when parse_response returns the BufReader is setup that it's position points to the next message that is in it's internal buffer and the stream has been completely consumed.

https://github.com/cyderize/rust-websocket/blob/master/src/client/response.rs#L45

```
    let response = try!(parse_response(reader));
```

This becomes a problem when begin() in response.rs is called to create a sender and receiver, this function throws away the previous BufReader by sending the inner stream to Receiver that creates a new BufReader so everything inside the old buffer that was ready to be parsed is lost.

https://github.com/cyderize/rust-websocket/blob/master/src/client/response.rs#L133

This issue is made more frequent by servos test suite because a lot of the tests send the first websocket message instantly after the handshake response, so the issue pops up there a lot more often.

I'll create a pull request with what I think is an easy solution to the problem but I'm not sure if it's the best thing to do.  It just moves the BufReader over to reciever instead of the internal stream.

**Comment by illegalprime** [comment]
thanks for the fix!
