### ISSUE TITLE
Link to documentation is broken (404 error)

### ISSUE THREAD

**Issue by aehernandez** [cyderize/rust-websocket#74]
The link given in the readme to view documentation gives a 404 error.
http://cyderize.github.io/rust-websocket/doc/websocket/

**Comment by cyderize** [comment]
Hmm, yeah something seems to have gone wrong with the Travis CI script for documenting. I'll take a look at it.

**Comment by aehernandez** [comment]
looks like the docs are back up! thanks!

**Comment by cyderize** [comment]
Yes, it turns out that using a newer version of rust simply fixed the problem (it was rust-lang/rust#32532).
