### ISSUE TITLE
support socket.io

### ISSUE THREAD

**Issue by arden** [cyderize/rust-websocket#76]
this lib does support socket.io?

**Comment by cyderize** [comment]
This library is simply a plain WebSocket library - there's no in-built support for Socket.IO.

It is possible to interface with Socket.IO servers/clients (provided they are using WebSocket and not AJAX/Flash), but that will require you to implement [the Socket.IO protocol](https://github.com/socketio/socket.io-protocol) yourself (and this is likely not an easy task).

**Comment by NeoLegends** [comment]
I'm currently working on a socket.io client for Rust.

**Comment by illegalprime** [comment]
closing this as it is out of the scope of this crate
