### ISSUE TITLE
server.try_accept() ?

### ISSUE THREAD

**Issue by Paul-Andre** [cyderize/rust-websocket#81]
Is there a non-blocking way to check if there is an incoming connection and get that connection if there is?

Something like server.accept() but that would return an Option and return None instead of waiting would be nice.

**Comment by illegalprime** [comment]
[Here](https://play.rust-lang.org/?gist=33e024821bba3b0ba4b6bada80db3ee3&version=stable&backtrace=0) is an example with a `TcpListener`.
The idea is calling `server.set_nonblocking(true)`, but this, unfortunately, can't currently be done.

Luckily it's really simple to implement, one just needs access to [this](https://github.com/cyderize/rust-websocket/blob/master/src/server/mod.rs#L79) member of the server struct to make that call.

Adding the following to the `Server` impl should do the trick:
```rust
pub fn set_nonblocking(&self, nonblocking: bool) -> Result<()> {
    self.inner.set_nonblocking(nonblocking)
}
```

Sorry this isn't already included, If you add this I feel @cyderize would merge it in, although I don't want to speak on his behalf.

**Comment by Paul-Andre** [comment]
Thanks. That works.

I made a similar thing for the Receiver as well.

Also, do you think it makes sense to add a set_nonblocking method to the sender?

**Comment by illegalprime** [comment]
Probably, can you open PR so I can get the full context?

**Comment by Paul-Andre** [comment]
I haven't tested whether the Receiver works yet, but will PR when I'm done.

**Comment by Paul-Andre** [comment]
Here's the pull request: https://github.com/cyderize/rust-websocket/pull/82

**Comment by illegalprime** [comment]
closing since #82 is merged.
