### ISSUE TITLE
Build fails on Windows: Cannot open include file: 'openssl/ssl.h': No such file or directory

### ISSUE THREAD

**Issue by markusl** [cyderize/rust-websocket#85]
`cargo run
   Compiling traitobject v0.0.1
   Compiling lazy_static v0.2.1
   Compiling unicode-normalization v0.1.2
   Compiling libc v0.2.10
   Compiling log v0.3.6
   Compiling language-tags v0.2.2
   Compiling winapi v0.2.6
   Compiling semver v0.1.20
   Compiling typeable v0.1.2
   Compiling pkg-config v0.3.8
   Compiling winapi-build v0.1.1
   Compiling mime v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling rand v0.3.14
   Compiling user32-sys v0.2.0
   Compiling openssl-sys v0.7.14
   Compiling num_cpus v0.2.13
   Compiling rustc_version v0.1.7
   Compiling cfg-if v0.1.0
   Compiling matches v0.1.2
   Compiling kernel32-sys v0.2.2
   Compiling unicode-bidi v0.2.3
   Compiling byteorder v0.5.1
   Compiling bitflags v0.7.0
   Compiling rustc-serialize v0.3.19
   Compiling unicase v1.4.0
   Compiling gcc v0.3.32
   Compiling httparse v1.1.2
   Compiling gdi32-sys v0.2.0
   Compiling hpack v0.2.0
   Compiling idna v0.1.0
   Compiling solicit v0.4.4
   Compiling openssl-sys-extras v0.7.14
   Compiling openssl v0.7.14
   Compiling url v1.2.0
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for openssl v0.7.14
Process didn't exit successfully: C:\prod\ws\target\debug\build\openssl-5464f8f6e728c35a\build-script-build (
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-pc-windows-msvc")
debug=true opt-level=0
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
running: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" "/nologo" "/MD" "/Z7"
s\target\debug\build\openssl-5464f8f6e728c35a\out\src\c_helpers.o" "/c" "src/c_helpers.c"
c_helpers.c
src/c_helpers.c(1): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
ExitStatus(ExitStatus(2))

command did not execute successfully, got: exit code: 2

--- stderr
thread '<main>' panicked at 'explicit panic', C:\Users\.cargo\registry\src\github.com-1ecc6299db9e\src\lib.rs:848
note: Run with `RUST_BACKTRACE=1` for a backtrace.

`

**Comment by illegalprime** [comment]
Can you try installing  the `openssl-sys` crate separately?

**Comment by brunoqc** [comment]
I have a similar problem but in my case it's `openssl/hmac.h`. 

I don't seem able to install `openssl-sys`:

```
C:\Users\Bruno\dev\rust\test [master]> cargo install openssl-sys
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: specified package has no binaries
```

**Comment by vi** [comment]
You can try building rust-websocket from my pull request (#90) without openssl. Obviously it won't support `wss://`.

**Comment by illegalprime** [comment]
@markusl you can now use this crate without openssl, but let me know if you're still having trouble with SSL.
