### ISSUE TITLE
tokio support

### ISSUE THREAD

**Issue by NeoLegends** [cyderize/rust-websocket#86]
It would be great if this library supported tokio-rs, it would really ease up the interop and composability of this library.

I'll study the source code and I will file a PR, if I'm confident I know enough about the source to make the changes, and if that feature is desirable enough.

**Comment by parris** [comment]
Hello! Did you ever do some research on this? Any ideas about how this could be supported? Thanks

**Comment by illegalprime** [comment]
@NeoLegends would love some help on getting tokio support in
