### ISSUE TITLE
Is it possible to modify the server.rs example to send the message to all clients connected to the server

### ISSUE THREAD

**Issue by ivanceras** [cyderize/rust-websocket#87]
https://github.com/cyderize/rust-websocket/blob/master/examples/server.rs

How do I send received messages to all connected clients in the server? Kind of like a massive open room, where everyone can hear anybody.

**Comment by illegalprime** [comment]
@ivanceras what's wrong with looping through all the connected clients?

**Comment by illegalprime** [comment]
you can check if there's any new messages by setting `nonblocking`, it would be easier if the library was made for evented things. 
closing for now.

**Comment by jackbit** [comment]
interested to know how to do it, can you give some example?

**Comment by illegalprime** [comment]
@jackbit yeah now it's easier with the added `tokio` support. I'm at work now so I can't write an example, but the idea is to split the clients into their readable and writable components, `select` on all the readable components + the server to get new clients, then make a chain and send to all the writable components of the clients.
