### ISSUE TITLE
tokio support

### ISSUE THREAD

**Issue by Yamakaky** [cyderize/rust-websocket#88]
https://github.com/tokio-rs/tokio

Did you consider it?

**Comment by vi** [comment]
@Yamakaky Is there any easy guide about how to "tokio-ify" a library?

**Comment by Yamakaky** [comment]
I don't think so ^^ You may want to ask on the gitter channel.

**Comment by illegalprime** [comment]
@Yamakaky yeah I do want to do it, I went to rust conf and got really excited about Futures so I've been wanting to add them. But then I also head `tokio` was going to implement its own websocket thing, I don't know that status of that.

**Comment by Yamakaky** [comment]
Maybe you can join efforts?

**Comment by illegalprime** [comment]
I'm currently adding `mio` support in the `ws-upgrade` branch, maybe first mio then tokio
