### ISSUE TITLE
Publish a version to crates.io which includes `WebSocketStream::set_nonblocking`

### ISSUE THREAD

**Issue by BonsaiDen** [cyderize/rust-websocket#89]
See commit: https://github.com/cyderize/rust-websocket/commit/3e738df3c219eaec3ff5b534d9aaf77c996c3811

Current workaround is to copy paste parts of the code, but it would be nicer to just have the relevant additions on crates.io :)

**Comment by sumproxy** [comment]
Really looking forward to an updated version on crates.io

**Comment by DenisKolodin** [comment]
The same.

**Comment by DenisKolodin** [comment]
@cyderize Could you help us? I've prepared https://github.com/cyderize/rust-websocket/pull/96 PR to solve this issue.
